import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'

export default function Home() {
    const [ isMobileSize, setIsMobileSize ] = useState(false);
    const [ data, setData ] = useState(null);
    const [ loading, setLoading ] = useState(true);
    const [ error, setError ] = useState(null);

    useEffect(() => {
        function newAdvice() {
            fetch('https://api.adviceslip.com/advice')
            .then(res => {return res.json()})
            .then(data => {
                setData(data);
                setError(null);
            })
            .catch((err) => {
                setError(err.message);
                setData(null);
            })
            .finally(setLoading(false));
        }
        document.getElementById('btn').addEventListener('click', newAdvice);
    }, [loading]);

    useEffect(() => {
        fetch('https://api.adviceslip.com/advice')
        .then(res => {return res.json()})
        .then(data => {
            setData(data);
            setError(null);
        })
        .catch((err) => {
            setError(err.message);
            setData(null);
        })
        .finally(setLoading(false));
    }, []);

    useEffect(() => {
        function handleResize() {
            if(window.innerWidth < 380) setIsMobileSize(true);
            else setIsMobileSize(false);
        }
        window.addEventListener('resize', handleResize);
    });
    
    return (
        <>
            <Head>
                <title>Advice Generator</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon-32x32.png" />
            </Head>
            <main className='flex flex-col items-center'>
                <div className='bg-dark_grayish_blue w-10/12 max-w-sm max-sm:p-3 max-sm:pb-8 mx-auto p-5 pb-8 rounded-lg flex flex-col items-center justify-center gap-3 shadow-xl'>
                {data && <h1 className='max-sm:text-[14px] text-[14px] text-neon_green font-light'>ADVICE #{data.slip.id}</h1>}
                    {loading ? 
                    <div role="status">
                        <svg aria-hidden="true" className="w-8 h-8 mr-2 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
                            <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
                        </svg>
                        <span className="sr-only">Loading...</span>
                    </div>: ''}
                    {error && <p>There is a problem fetching the post data - {error}</p>}
                    {data && <p className='max-sm:text-xs text-xs text-light_cyan font-medium text-center'>{data.slip.advice}</p>}
                    <div className='w-full h-fit flex flex-row gap-4'>
                        <div className='w-full flex items-center justify-center'>
                            <img src={isMobileSize ? '/pattern-divider-mobile.svg' : '/pattern-divider-desktop.svg'} alt='divider'></img>
                        </div>
                    </div>
                </div>
                <button id='btn' disabled={loading} className={!loading ? 'relative bottom-[30px] flex items-center justify-center bg-neon_green hover:shadow-[0_0_20px_hsl(150,100%,66%)] duration-300 w-9 h-9 rounded-full' : 'relative bottom-[30px] flex items-center justify-center bg-dark_blue hover:shadow-[0_0_20px_hsl(150,100%,66%)] duration-300 w-9 h-9 rounded-full'}>
                    <Image src={'/icon-dice.svg'} width={22} height={22} alt='dice'></Image>
                </button>
            </main>
        </>
    )
}
